# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/duan/work/SXFEL_GUI/emittance.ui'
#
# Created: Sun Mar  6 11:48:51 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1023, 740)
        Dialog.setAutoFillBackground(True)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(380, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_start = QtGui.QPushButton(Dialog)
        self.pushButton_start.setGeometry(QtCore.QRect(410, 480, 81, 41))
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(40, 390, 361, 321))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.comboBox_prof_select = QtGui.QComboBox(self.groupBox)
        self.comboBox_prof_select.setGeometry(QtCore.QRect(20, 50, 131, 21))
        self.comboBox_prof_select.setObjectName(_fromUtf8("comboBox_prof_select"))
        self.comboBox_prof_select.addItem(_fromUtf8(""))
        self.comboBox_prof_select.addItem(_fromUtf8(""))
        self.comboBox_prof_select.addItem(_fromUtf8(""))
        self.comboBox_prof_select.addItem(_fromUtf8(""))
        self.comboBox_prof_select.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 80, 331, 216))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.checkBox_q2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_q2.setChecked(True)
        self.checkBox_q2.setObjectName(_fromUtf8("checkBox_q2"))
        self.gridLayout_2.addWidget(self.checkBox_q2, 2, 0, 1, 1)
        self.checkBox_q3 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_q3.setChecked(True)
        self.checkBox_q3.setObjectName(_fromUtf8("checkBox_q3"))
        self.gridLayout_2.addWidget(self.checkBox_q3, 3, 0, 1, 1)
        self.lineEdit_q1k_from = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_q1k_from.setObjectName(_fromUtf8("lineEdit_q1k_from"))
        self.gridLayout_2.addWidget(self.lineEdit_q1k_from, 1, 1, 1, 1)
        self.checkBox_q1 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_q1.setChecked(True)
        self.checkBox_q1.setObjectName(_fromUtf8("checkBox_q1"))
        self.gridLayout_2.addWidget(self.checkBox_q1, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_q2k_to = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_q2k_to.setObjectName(_fromUtf8("lineEdit_q2k_to"))
        self.gridLayout_2.addWidget(self.lineEdit_q2k_to, 2, 2, 1, 1)
        self.lineEdit_q3k_to = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_q3k_to.setObjectName(_fromUtf8("lineEdit_q3k_to"))
        self.gridLayout_2.addWidget(self.lineEdit_q3k_to, 3, 2, 1, 1)
        self.lineEdit_q3k_from = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_q3k_from.setObjectName(_fromUtf8("lineEdit_q3k_from"))
        self.gridLayout_2.addWidget(self.lineEdit_q3k_from, 3, 1, 1, 1)
        self.lineEdit_q1k_to = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_q1k_to.setObjectName(_fromUtf8("lineEdit_q1k_to"))
        self.gridLayout_2.addWidget(self.lineEdit_q1k_to, 1, 2, 1, 1)
        self.lineEdit_q2k_from = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_q2k_from.setObjectName(_fromUtf8("lineEdit_q2k_from"))
        self.gridLayout_2.addWidget(self.lineEdit_q2k_from, 2, 1, 1, 1)
        self.lineEdit_samples = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_samples.setObjectName(_fromUtf8("lineEdit_samples"))
        self.gridLayout_2.addWidget(self.lineEdit_samples, 7, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.lineEdit_steps = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_steps.setObjectName(_fromUtf8("lineEdit_steps"))
        self.gridLayout_2.addWidget(self.lineEdit_steps, 6, 1, 1, 1)
        self.checkBox_y_plane = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_y_plane.setChecked(True)
        self.checkBox_y_plane.setObjectName(_fromUtf8("checkBox_y_plane"))
        self.gridLayout_2.addWidget(self.checkBox_y_plane, 5, 1, 1, 1)
        self.checkBox_x_plane = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_x_plane.setChecked(True)
        self.checkBox_x_plane.setObjectName(_fromUtf8("checkBox_x_plane"))
        self.gridLayout_2.addWidget(self.checkBox_x_plane, 5, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(640, 410, 331, 301))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 271, 81))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_ex = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_ex.setObjectName(_fromUtf8("lineEdit_ex"))
        self.gridLayout.addWidget(self.lineEdit_ex, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setMouseTracking(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.lineEdit_ey = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_ey.setObjectName(_fromUtf8("lineEdit_ey"))
        self.gridLayout.addWidget(self.lineEdit_ey, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setMouseTracking(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 140, 281, 151))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_alphax = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_alphax.setObjectName(_fromUtf8("lineEdit_alphax"))
        self.gridLayout_3.addWidget(self.lineEdit_alphax, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget1)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.lineEdit_betax = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_betax.setObjectName(_fromUtf8("lineEdit_betax"))
        self.gridLayout_3.addWidget(self.lineEdit_betax, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget1)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 2, 0, 1, 1)
        self.lineEdit_gammax = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_gammax.setObjectName(_fromUtf8("lineEdit_gammax"))
        self.gridLayout_3.addWidget(self.lineEdit_gammax, 2, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget1)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 0, 2, 1, 1)
        self.lineEdit_alphay = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_alphay.setObjectName(_fromUtf8("lineEdit_alphay"))
        self.gridLayout_3.addWidget(self.lineEdit_alphay, 0, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget1)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 1, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget1)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 2, 2, 1, 1)
        self.lineEdit_betay = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_betay.setObjectName(_fromUtf8("lineEdit_betay"))
        self.gridLayout_3.addWidget(self.lineEdit_betay, 1, 3, 1, 1)
        self.lineEdit_gammay = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_gammay.setObjectName(_fromUtf8("lineEdit_gammay"))
        self.gridLayout_3.addWidget(self.lineEdit_gammay, 2, 3, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 60, 131, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.checkBox_onsite = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_onsite.setGeometry(QtCore.QRect(10, 60, 91, 19))
        self.checkBox_onsite.setObjectName(_fromUtf8("checkBox_onsite"))
        self.checkBox_simu = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_simu.setGeometry(QtCore.QRect(10, 30, 111, 19))
        self.checkBox_simu.setChecked(True)
        self.checkBox_simu.setObjectName(_fromUtf8("checkBox_simu"))
        self.pushButton_stop = QtGui.QPushButton(Dialog)
        self.pushButton_stop.setGeometry(QtCore.QRect(510, 480, 81, 41))
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 720, 241, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(420, 560, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.mplwidget1 = MatplotlibWidget(Dialog)
        self.mplwidget1.setGeometry(QtCore.QRect(190, 50, 351, 281))
        self.mplwidget1.setObjectName(_fromUtf8("mplwidget1"))
        self.mplwidget2 = MatplotlibWidget(Dialog)
        self.mplwidget2.setGeometry(QtCore.QRect(580, 50, 351, 281))
        self.mplwidget2.setObjectName(_fromUtf8("mplwidget2"))
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(420, 540, 111, 21))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.label_progress = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_progress.setObjectName(_fromUtf8("label_progress"))
        self.horizontalLayout.addWidget(self.label_progress)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Emittance Measurement", None))
        self.pushButton_start.setText(_translate("Dialog", "START", None))
        self.groupBox.setTitle(_translate("Dialog", "Configuration", None))
        self.comboBox_prof_select.setItemText(0, _translate("Dialog", "PROF01L0", None))
        self.comboBox_prof_select.setItemText(1, _translate("Dialog", "Q03", None))
        self.comboBox_prof_select.setItemText(2, _translate("Dialog", "Q05", None))
        self.comboBox_prof_select.setItemText(3, _translate("Dialog", "Q09", None))
        self.comboBox_prof_select.setItemText(4, _translate("Dialog", "Q11", None))
        self.label_2.setText(_translate("Dialog", "Select Profile", None))
        self.label_3.setText(_translate("Dialog", "K_to", None))
        self.label_4.setText(_translate("Dialog", "K_from", None))
        self.checkBox_q2.setText(_translate("Dialog", "Q02L0", None))
        self.checkBox_q3.setText(_translate("Dialog", "Q03L0", None))
        self.lineEdit_q1k_from.setText(_translate("Dialog", "0", None))
        self.checkBox_q1.setText(_translate("Dialog", "Q01L0", None))
        self.label_5.setText(_translate("Dialog", "Quad", None))
        self.lineEdit_q2k_to.setText(_translate("Dialog", "0", None))
        self.lineEdit_q3k_to.setText(_translate("Dialog", "10", None))
        self.lineEdit_q3k_from.setText(_translate("Dialog", "0", None))
        self.lineEdit_q1k_to.setText(_translate("Dialog", "10", None))
        self.lineEdit_q2k_from.setText(_translate("Dialog", "-10", None))
        self.lineEdit_samples.setText(_translate("Dialog", "1", None))
        self.label_7.setText(_translate("Dialog", "Samples", None))
        self.label_6.setText(_translate("Dialog", "Steps", None))
        self.lineEdit_steps.setText(_translate("Dialog", "21", None))
        self.checkBox_y_plane.setText(_translate("Dialog", "Y Plane", None))
        self.checkBox_x_plane.setText(_translate("Dialog", "X Plane", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Measurement Results", None))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">ε</span><span style=\" font-size:14pt; vertical-align:sub;\">x</span><span style=\" font-size:14pt;\">=</span></p></body></html>", None))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">mm·mrad</span></p></body></html>", None))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">ε</span><span style=\" font-size:14pt; vertical-align:sub;\">y</span><span style=\" font-size:14pt;\">=</span></p></body></html>", None))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">mm·mrad</span></p></body></html>", None))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">α</span><span style=\" font-size:14pt; vertical-align:sub;\">x</span><span style=\" font-size:14pt;\">=</span></p></body></html>", None))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">β</span><span style=\" font-size:14pt; vertical-align:sub;\">x</span><span style=\" font-size:14pt;\">=</span></p></body></html>", None))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">γ</span><span style=\" font-size:14pt; vertical-align:sub;\">x</span><span style=\" font-size:14pt;\">=</span></p></body></html>", None))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">α</span><span style=\" font-size:14pt; vertical-align:sub;\">y</span><span style=\" font-size:14pt;\">=</span></p></body></html>", None))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">β</span><span style=\" font-size:14pt; vertical-align:sub;\">y</span><span style=\" font-size:14pt;\">=</span></p></body></html>", None))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">γ</span><span style=\" font-size:14pt; vertical-align:sub;\">y</span><span style=\" font-size:14pt;\">=</span></p></body></html>", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Mode", None))
        self.checkBox_onsite.setText(_translate("Dialog", "On Site", None))
        self.checkBox_simu.setText(_translate("Dialog", "Simulation", None))
        self.pushButton_stop.setText(_translate("Dialog", "Stop", None))
        self.label_8.setText(_translate("Dialog", "v0.2-160302 guduan@sinap.ac.cn", None))
        self.label_9.setText(_translate("Dialog", "Progress:", None))
        self.label_progress.setText(_translate("Dialog", "0", None))
        self.label_10.setText(_translate("Dialog", "%", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

