# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\work\SXFEL_GUI\energy.ui'
#
# Created: Sat Mar 05 14:17:54 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(951, 677)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 311, 561))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.comboBox_b_select = QtGui.QComboBox(self.groupBox)
        self.comboBox_b_select.setGeometry(QtCore.QRect(10, 40, 87, 22))
        self.comboBox_b_select.setObjectName(_fromUtf8("comboBox_b_select"))
        self.comboBox_b_select.addItem(_fromUtf8(""))
        self.comboBox_b_select.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 131, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_designed_energy = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_designed_energy.setGeometry(QtCore.QRect(130, 40, 91, 21))
        self.lineEdit_designed_energy.setObjectName(_fromUtf8("lineEdit_designed_energy"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(220, 40, 31, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 72, 15))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(130, 70, 151, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_profile = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_profile.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.lineEdit_profile.setObjectName(_fromUtf8("lineEdit_profile"))
        self.lineEdit_designed_dispersion = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_designed_dispersion.setGeometry(QtCore.QRect(130, 90, 91, 21))
        self.lineEdit_designed_dispersion.setObjectName(_fromUtf8("lineEdit_designed_dispersion"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 141, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 180, 41, 331))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 160, 241, 370))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 1, 1, 1)
        self.splitter = QtGui.QSplitter(self.layoutWidget1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.lineEdit_amp_a2 = QtGui.QLineEdit(self.splitter)
        self.lineEdit_amp_a2.setObjectName(_fromUtf8("lineEdit_amp_a2"))
        self.lineEdit_pha_a2 = QtGui.QLineEdit(self.splitter)
        self.lineEdit_pha_a2.setObjectName(_fromUtf8("lineEdit_pha_a2"))
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 2)
        self.splitter_2 = QtGui.QSplitter(self.layoutWidget1)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.horizontalScrollBar_amp_a2 = QtGui.QScrollBar(self.splitter_2)
        self.horizontalScrollBar_amp_a2.setMaximum(400)
        self.horizontalScrollBar_amp_a2.setProperty("value", 400)
        self.horizontalScrollBar_amp_a2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_amp_a2.setObjectName(_fromUtf8("horizontalScrollBar_amp_a2"))
        self.horizontalScrollBar_pha_a2 = QtGui.QScrollBar(self.splitter_2)
        self.horizontalScrollBar_pha_a2.setMaximum(1800)
        self.horizontalScrollBar_pha_a2.setProperty("value", 900)
        self.horizontalScrollBar_pha_a2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_pha_a2.setObjectName(_fromUtf8("horizontalScrollBar_pha_a2"))
        self.gridLayout.addWidget(self.splitter_2, 2, 0, 1, 2)
        self.lineEdit_amp_a3 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_amp_a3.setObjectName(_fromUtf8("lineEdit_amp_a3"))
        self.gridLayout.addWidget(self.lineEdit_amp_a3, 3, 0, 1, 1)
        self.lineEdit_pha_a3 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_pha_a3.setObjectName(_fromUtf8("lineEdit_pha_a3"))
        self.gridLayout.addWidget(self.lineEdit_pha_a3, 3, 1, 1, 1)
        self.horizontalScrollBar_amp_a3 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_amp_a3.setMaximum(400)
        self.horizontalScrollBar_amp_a3.setProperty("value", 400)
        self.horizontalScrollBar_amp_a3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_amp_a3.setObjectName(_fromUtf8("horizontalScrollBar_amp_a3"))
        self.gridLayout.addWidget(self.horizontalScrollBar_amp_a3, 4, 0, 1, 1)
        self.horizontalScrollBar_pha_a3 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_pha_a3.setMaximum(1800)
        self.horizontalScrollBar_pha_a3.setProperty("value", 900)
        self.horizontalScrollBar_pha_a3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_pha_a3.setObjectName(_fromUtf8("horizontalScrollBar_pha_a3"))
        self.gridLayout.addWidget(self.horizontalScrollBar_pha_a3, 4, 1, 1, 1)
        self.lineEdit_amp_a4 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_amp_a4.setObjectName(_fromUtf8("lineEdit_amp_a4"))
        self.gridLayout.addWidget(self.lineEdit_amp_a4, 5, 0, 1, 1)
        self.lineEdit_pha_a4 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_pha_a4.setObjectName(_fromUtf8("lineEdit_pha_a4"))
        self.gridLayout.addWidget(self.lineEdit_pha_a4, 5, 1, 1, 1)
        self.horizontalScrollBar_amp_a4 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_amp_a4.setMaximum(465)
        self.horizontalScrollBar_amp_a4.setSingleStep(1)
        self.horizontalScrollBar_amp_a4.setProperty("value", 465)
        self.horizontalScrollBar_amp_a4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_amp_a4.setObjectName(_fromUtf8("horizontalScrollBar_amp_a4"))
        self.gridLayout.addWidget(self.horizontalScrollBar_amp_a4, 6, 0, 1, 1)
        self.horizontalScrollBar_pha_a4 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_pha_a4.setMaximum(1800)
        self.horizontalScrollBar_pha_a4.setProperty("value", 900)
        self.horizontalScrollBar_pha_a4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_pha_a4.setObjectName(_fromUtf8("horizontalScrollBar_pha_a4"))
        self.gridLayout.addWidget(self.horizontalScrollBar_pha_a4, 6, 1, 1, 1)
        self.lineEdit_amp_a5 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_amp_a5.setObjectName(_fromUtf8("lineEdit_amp_a5"))
        self.gridLayout.addWidget(self.lineEdit_amp_a5, 7, 0, 1, 1)
        self.lineEdit_pha_a5 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_pha_a5.setObjectName(_fromUtf8("lineEdit_pha_a5"))
        self.gridLayout.addWidget(self.lineEdit_pha_a5, 7, 1, 1, 1)
        self.horizontalScrollBar_amp_a5 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_amp_a5.setMaximum(465)
        self.horizontalScrollBar_amp_a5.setProperty("value", 465)
        self.horizontalScrollBar_amp_a5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_amp_a5.setObjectName(_fromUtf8("horizontalScrollBar_amp_a5"))
        self.gridLayout.addWidget(self.horizontalScrollBar_amp_a5, 8, 0, 1, 1)
        self.horizontalScrollBar_pha_a5 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_pha_a5.setMaximum(1800)
        self.horizontalScrollBar_pha_a5.setProperty("value", 900)
        self.horizontalScrollBar_pha_a5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_pha_a5.setObjectName(_fromUtf8("horizontalScrollBar_pha_a5"))
        self.gridLayout.addWidget(self.horizontalScrollBar_pha_a5, 8, 1, 1, 1)
        self.lineEdit_amp_a6 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_amp_a6.setObjectName(_fromUtf8("lineEdit_amp_a6"))
        self.gridLayout.addWidget(self.lineEdit_amp_a6, 9, 0, 1, 1)
        self.lineEdit_pha_a6 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_pha_a6.setObjectName(_fromUtf8("lineEdit_pha_a6"))
        self.gridLayout.addWidget(self.lineEdit_pha_a6, 9, 1, 1, 1)
        self.horizontalScrollBar_amp_a6 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_amp_a6.setMaximum(465)
        self.horizontalScrollBar_amp_a6.setProperty("value", 465)
        self.horizontalScrollBar_amp_a6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_amp_a6.setObjectName(_fromUtf8("horizontalScrollBar_amp_a6"))
        self.gridLayout.addWidget(self.horizontalScrollBar_amp_a6, 10, 0, 1, 1)
        self.horizontalScrollBar_pha_a6 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_pha_a6.setMaximum(1800)
        self.horizontalScrollBar_pha_a6.setProperty("value", 900)
        self.horizontalScrollBar_pha_a6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_pha_a6.setObjectName(_fromUtf8("horizontalScrollBar_pha_a6"))
        self.gridLayout.addWidget(self.horizontalScrollBar_pha_a6, 10, 1, 1, 1)
        self.lineEdit_amp_a7 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_amp_a7.setObjectName(_fromUtf8("lineEdit_amp_a7"))
        self.gridLayout.addWidget(self.lineEdit_amp_a7, 11, 0, 1, 1)
        self.lineEdit_pha_a7 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_pha_a7.setObjectName(_fromUtf8("lineEdit_pha_a7"))
        self.gridLayout.addWidget(self.lineEdit_pha_a7, 11, 1, 1, 1)
        self.horizontalScrollBar_amp_a7 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_amp_a7.setMaximum(465)
        self.horizontalScrollBar_amp_a7.setProperty("value", 465)
        self.horizontalScrollBar_amp_a7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_amp_a7.setObjectName(_fromUtf8("horizontalScrollBar_amp_a7"))
        self.gridLayout.addWidget(self.horizontalScrollBar_amp_a7, 12, 0, 1, 1)
        self.horizontalScrollBar_pha_a7 = QtGui.QScrollBar(self.layoutWidget1)
        self.horizontalScrollBar_pha_a7.setMaximum(1800)
        self.horizontalScrollBar_pha_a7.setProperty("value", 900)
        self.horizontalScrollBar_pha_a7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_pha_a7.setObjectName(_fromUtf8("horizontalScrollBar_pha_a7"))
        self.gridLayout.addWidget(self.horizontalScrollBar_pha_a7, 12, 1, 1, 1)
        self.pushButton_set = QtGui.QPushButton(self.groupBox)
        self.pushButton_set.setGeometry(QtCore.QRect(70, 530, 93, 28))
        self.pushButton_set.setObjectName(_fromUtf8("pushButton_set"))
        self.pushButton_default = QtGui.QPushButton(self.groupBox)
        self.pushButton_default.setGeometry(QtCore.QRect(190, 530, 93, 28))
        self.pushButton_default.setObjectName(_fromUtf8("pushButton_default"))
        self.pushButton_start = QtGui.QPushButton(self.centralWidget)
        self.pushButton_start.setGeometry(QtCore.QRect(770, 130, 93, 41))
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.pushButton_pause = QtGui.QPushButton(self.centralWidget)
        self.pushButton_pause.setGeometry(QtCore.QRect(770, 200, 93, 41))
        self.pushButton_pause.setObjectName(_fromUtf8("pushButton_pause"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(750, 450, 160, 151))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.lineEdit_energy = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_energy.setObjectName(_fromUtf8("lineEdit_energy"))
        self.verticalLayout_2.addWidget(self.lineEdit_energy)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_2.addWidget(self.label_17)
        self.lineEdit_energy_spread = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_energy_spread.setText(_fromUtf8(""))
        self.lineEdit_energy_spread.setObjectName(_fromUtf8("lineEdit_energy_spread"))
        self.verticalLayout_2.addWidget(self.lineEdit_energy_spread)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(340, 20, 361, 361))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vbox_mpl1 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vbox_mpl1.setMargin(0)
        self.vbox_mpl1.setObjectName(_fromUtf8("vbox_mpl1"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(340, 390, 361, 261))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.vbox_mpl2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vbox_mpl2.setMargin(0)
        self.vbox_mpl2.setObjectName(_fromUtf8("vbox_mpl2"))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Configuration", None))
        self.comboBox_b_select.setItemText(0, _translate("MainWindow", "B2", None))
        self.comboBox_b_select.setItemText(1, _translate("MainWindow", "B3", None))
        self.label.setText(_translate("MainWindow", "Magnet", None))
        self.label_2.setText(_translate("MainWindow", "Designed Energy", None))
        self.lineEdit_designed_energy.setText(_translate("MainWindow", "92.99", None))
        self.label_3.setText(_translate("MainWindow", "MeV", None))
        self.label_4.setText(_translate("MainWindow", "Profile", None))
        self.label_5.setText(_translate("MainWindow", "Designed Dispersion", None))
        self.lineEdit_profile.setText(_translate("MainWindow", "Prof B2", None))
        self.lineEdit_designed_dispersion.setText(_translate("MainWindow", "0.9877", None))
        self.label_6.setText(_translate("MainWindow", "Acc.Modules Setup", None))
        self.label_7.setText(_translate("MainWindow", "A2", None))
        self.label_9.setText(_translate("MainWindow", "A3", None))
        self.label_10.setText(_translate("MainWindow", "A4", None))
        self.label_11.setText(_translate("MainWindow", "A5", None))
        self.label_12.setText(_translate("MainWindow", "A6", None))
        self.label_13.setText(_translate("MainWindow", "A7", None))
        self.label_14.setText(_translate("MainWindow", "Amp.(MV)", None))
        self.label_15.setText(_translate("MainWindow", "Phase(degree)", None))
        self.lineEdit_amp_a2.setText(_translate("MainWindow", "40", None))
        self.lineEdit_pha_a2.setText(_translate("MainWindow", "66.4", None))
        self.lineEdit_amp_a3.setText(_translate("MainWindow", "40", None))
        self.lineEdit_pha_a3.setText(_translate("MainWindow", "66.4", None))
        self.lineEdit_amp_a4.setText(_translate("MainWindow", "46.5", None))
        self.lineEdit_pha_a4.setText(_translate("MainWindow", "112", None))
        self.lineEdit_amp_a5.setText(_translate("MainWindow", "46.5", None))
        self.lineEdit_pha_a5.setText(_translate("MainWindow", "112", None))
        self.lineEdit_amp_a6.setText(_translate("MainWindow", "46.5", None))
        self.lineEdit_pha_a6.setText(_translate("MainWindow", "112", None))
        self.lineEdit_amp_a7.setText(_translate("MainWindow", "46.5", None))
        self.lineEdit_pha_a7.setText(_translate("MainWindow", "112", None))
        self.pushButton_set.setText(_translate("MainWindow", "Set", None))
        self.pushButton_default.setText(_translate("MainWindow", "Default", None))
        self.pushButton_start.setText(_translate("MainWindow", "Start", None))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause", None))
        self.label_16.setText(_translate("MainWindow", "Energy (MeV)", None))
        self.label_17.setText(_translate("MainWindow", "Energy Spread (%)", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

